name: Debugging

on:
  workflow_dispatch:

jobs:
  add-debug-commit:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CI_COMMIT_AUTHOR: "Continuous Integration"
      CI_COMMIT_MESSAGE: "Statefile update"
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "honestwork" >> .gitignore
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git add .gitignore
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
