name: "Netlify Deploy"

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: 'Deployment'
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == 'Statefile update' }}
    defaults:
      run:
        working-directory: visualiser/
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.CD_GIT_TOKEN }}
      - uses: actions/setup-node@v3
      - uses: lucapericlp/action-netlify-deploy@master
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy v${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          WORKING_DIRECTORY: visualiser/
