name: Update statefile

on:
  schedule:
    - cron: '55 23 * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    name: Rust project
    runs-on: ubuntu-latest
    env:
      RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      RUST_BACKTRACE: "1"
      CI_COMMIT_AUTHOR: "Continuous Integration"
      CI_COMMIT_MESSAGE: "Statefile update"
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.CD_GIT_TOKEN }}
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.79.0
          default: true
          override: true

      - uses: Swatinem/rust-cache@v2

      - name: Setup Rclone
        uses: AnimMouse/setup-rclone@v1
        with:
          rclone_config: ${{ secrets.RCLONE_CONFIG }}

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Compute latest statefile
        uses: actions-rs/cargo@v1
        with:
          command: run

      - name: Commit statefile
        run: |
          echo "Ran by ${GITHUB_ACTOR}..."
          git_diff_output=$(git diff)
          if [ -z "$git_diff_output" ]; then
            echo "Statefile wasn't updated after all..."
          else
            git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
            git config --global user.email "username@users.noreply.github.com"
            git add visualiser/src/state_file.json
            git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
            git push
          fi
